### ISSUE TITLE
Support multiple WARs inside a single EAR 

### ISSUE THREAD

**Issue by mrts** [kumm/flow-cdi-addon#4]
Vaadin 8 CDI add-on does not support multiple CDI UIs in separate WARs inside a single EAR, see https://github.com/vaadin/cdi/issues/97.

I'm not sure if using CDI 1.2 or 2.0 makes this possible or not, but that would definitely be a "killer feature" for people building large modular applications that consist of multiple WARs and EJB JARs.

Or maybe it just works in newer application servers (I haven't tested myself)? [Here's](https://github.com/mrts/local-ejb-injection) an example of a basic multi-module EAR that can be used as the blueprint just in case.

**Comment by kumm** [comment]
Issue is relevant for V10, but title should be changed. There are no CDI UIs scanned by CDI.

Checked the issue from V8 CDI addon.
Maybe it describes a behavior that changed after fixing this issue: https://issues.jboss.org/browse/WELD-2143

Maybe things changed. 
But just start a search for "CDI extension EAR", or similar keywords.
It is still a nasty area with unclear specs, and container specific implementations.
I had reasons when WAR became the new EAR for me several years ago :)

Will do some experiment, but currently it does not seem an easy one.

**Comment by mrts** [comment]
Right, thanks :)! Please feel free to change the title to make it more clear for V10. Fingers crossed for the experiment :)!

**Comment by kumm** [comment]
I have not got good news.
Even plain Vaadin without this addon does not start up on TomEE 7.
"com.vaadin.flow.server.startup.ServletDeployer.contextInitialized Skipping automatic servlet registration because there are no navigation targets annotated with @Route"

I have succeeded starting up plain Vaadin on Wildfly 11,12, and Payarra 4.1,5. Did not check others.

I have tried to startup with this cdi addon on the remaining 4 containers, but failed.
It seems on wildfly I have encountered something like this bug: https://issues.jboss.org/browse/WELD-2250
On payara logs did not help.

Experimental tests can be found at ear-cdi branch. ( cf0f67e )

Going to ping TomEE and Weld projects.

**Comment by kumm** [comment]
Blocked by
https://issues.jboss.org/browse/WELD-2250
https://issues.apache.org/jira/browse/TOMEE-2192

**Comment by mrts** [comment]
@kumm https://issues.jboss.org/browse/WELD-2250 status is _Done/Resolved_ now and Weld 3.0.5 seems to be [part of WildFly 14](https://repository.jboss.org/nexus/content/groups/public/org/wildfly/wildfly-component-matrix/14.0.0.Final/wildfly-component-matrix-14.0.0.Final.pom). Maybe it's a good time to re-run the test on WildFly 14?

**Comment by kumm** [comment]
Wildfly 14 with Weld 3.0.5 passes my quick test. 
Payara 5.183 with Weld 3.0.5 fails with a strange error about deltaspike
```
  Exception during lifecycle processing
org.glassfish.deployment.common.DeploymentException: CDI deployment failure:Error instantiating :org.apache.deltaspike.core.api.provider.BeanManagerProvider -- Error instantiating :org.apache.deltaspike.core.api.provider.BeanManagerProvider
	at org.jboss.weld.util.ServiceLoader.createInstance(ServiceLoader.java:315)
```

https://issues.apache.org/jira/browse/TOMEE-2192 is not resolved, but it turned out the bug affects tomee arquillian. 
A manually deployed test application to TomEE 7.0.4 passes a quick manual test.

There are some container specific issues affecting EAR and CDI, but it seems there is nothing to do in this addon to support ears.
Closing this issue.

**Comment by mrts** [comment]
Whoa, wait, did I get you right that two Vaadin 10 WARs using the CDI extension in a single EAR actually worked in WildFly 14?

**Comment by kumm** [comment]
Yes, it did work. Vaadin 10 and CDI addon is packaged in each war.

**Comment by mrts** [comment]
Many thanks, I tried it out with WildFly 14 and Vaadin 12, works like a charm!

Here's a simple sample:

https://gitlab.com/mrts/vaadin12-javaee-multiple-wars-in-one-ear
